### ISSUE TITLE
Duplicate Error

### ISSUE THREAD

**Issue by can-cc** [artemyarulin/react-native-xml#2]
I got error message when i installed. Can you help me?

```
This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/Users/chchen/MY-PROJECT/ReactFeed/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:162:15)
    at /Users/chchen/MY-PROJECT/ReactFeed/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:127:25
Rebuilding haste map to recover from error:
Error: @providesModule naming collision:
  Duplicate module name: SpringConfig
  Paths: /Users/chchen/MY-PROJECT/ReactFeed/Pods/React/Libraries/Animated/SpringConfig.js collides with /Users/chchen/MY-PROJECT/ReactFeed/node_modules/react-native/Libraries/Animated/src/SpringConfig.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/Users/chchen/MY-PROJECT/ReactFeed/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:162:15)
    at /Users/chchen/MY-PROJECT/ReactFeed/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:127:25
Rebuilding haste map to recover from error:
Error: @providesModule naming collision:
  Duplicate module name: AppRegistry
  Paths: /Users/chchen/MY-PROJECT/ReactFeed/Pods/React/Libraries/AppRegistry/AppRegistry.js collides with /Users/chchen/MY-PROJECT/ReactFeed/node_modules/react-native/Libraries/AppRegistry/AppRegistry.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/Users/chchen/MY-PROJECT/ReactFeed/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:162:15)
    at /Users/chchen/MY-PROJECT/ReactFeed/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:127:25
Rebuilding haste map to recover from error:
Error: @providesModule naming collision:
  Duplicate module name: AppStateIOS
  Paths: /Users/chchen/MY-PROJECT/ReactFeed/Pods/React/Libraries/AppStateIOS/AppStateIOS.ios.js collides with /Users/chchen/MY-PROJECT/ReactFeed/node_modules/react-native/Libraries/AppStateIOS/AppStateIOS.ios.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/Users/chchen/MY-PROJECT/ReactFeed/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:162:15)
    at /Users/chchen/MY-PROJECT/ReactFeed/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:127:25
Rebuilding haste map to recover from error:
Error: @providesModule naming collision:
  Duplicate module name: ActionSheetIOS
  Paths: /Users/chchen/MY-PROJECT/ReactFeed/Pods/React/Libraries/ActionSheetIOS/ActionSheetIOS.js collides with /Users/chchen/MY-PROJECT/ReactFeed/node_modules/react-native/Libraries/ActionSheetIOS/ActionSheetIOS.js
```

**Comment by artemyarulin** [comment]
Hi... hm... oh I got it. Once you installed the library using CocoaPod you also get React Native as a dependency, although you have it in node_modules already, result - conflict. I didn't update the library for a while and nowadays there are better ways how to distribute libraries I guess.

Unfortunately I don't have time now to update the library. One way for you to fix it I guess would be simply copy and paste `rnxml/rnxml/RNMXml.{h,m}` to your project.
